### ISSUE TITLE
Add possibility to create a recipe for a file/directory

### ISSUE THREAD

**Issue by bochoven** [homebysix/recipe-robot#105]
For things like license files, I have to create a recipe manually that packages the file so I can distribute it with munki.

It would be nice if recipe robot could create a recipe based on a file or directory. The recipe would have to create a package that would install the file (or directory structure) with the correct permissions.

**Comment by homebysix** [comment]
Hi @bochoven. Since the license file (presumably) doesn't change with every version of its associated app, do you really need an AutoPkg recipe for it? Wouldn't it be simpler to build a one-off [MunkiPkg](https://github.com/munki/munki-pkg) project with the proper payload?

I've used MunkiPkg to create TextExpander, Sublime Text, and 1Password license packages and deploy them with Munki. I sometimes have to change them when a new major version is released, but not for each minor version.

**Comment by sheagcraig** [comment]
Just to chime in too-for stuff like this I just duplicate a git project that I have sitting around for a Luggage package. Probably a little more work (but a little more control) than MunkiPkg. But this is how I do a lot of my "not-likely-to-change" configuration packages. That way you've got it in version control, and can make changes and pump out new versions quickly when needed.
