### ISSUE TITLE
Consider how we read and write plists

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#16]
Right now we're doing what AutoPkg does, which is this:

```
try:
    from recipe_robot_lib import FoundationPlist
except:
    print '[WARNING] importing plistlib as FoundationPlist'
    import plistlib as FoundationPlist
```

@sheagcraig mentioned that we might use neither FoundationPlist nor plistlib, and instead "use the preferences system correctly." I don't yet know what this means, but I want to make an issue here for reference.

**Comment by sheagcraig** [comment]
So what I'm talking about is that if you open a plist and parse it, you're
committing to only supporting that _file_. It means that configuration
profiles cannot be used.
>
>
When a mac app checks for a preference, it does a
`NSUserDefaults.stringForKey("prefyourinterestedin")`, which checks the
preferences system for the value. It doesn't open a file, parse it, and
then look for a particular key in that file object. It lets the CFPrefsD
system handle that. CFPrefsd has all of that stuff cached and aggregated.

Now, do we need Recipe Robot to be able to use a configuration profile? No.

Is it so heinous to include FoundationPlist? No (python-jss does... for
now).

Is it trivial to just use PyObjC to set and get the preferences directly?
Yes.

The above things don't really swing it one way or the other for me.

BUT... If you want to have preferences for the GUI, AND you want them to be
in the same preference domain as the recipe robot python script, it would
make sense to have them do everything through NSUserDefaults since the
Swift or ObjectiveC code won't have a choice.

**Comment by homebysix** [comment]
OK, I'm convinced. Let's switch to PyObjC / NSUserDefaults. Want to search for references to FoundationPlist and make the appropriate changes?

**Comment by eahrold** [comment]
If your doing this maybe we should us nsurlconnection

**Comment by sheagcraig** [comment]
@eahrold Do you mean add NSURLConnection for GET requests? I'm not smart enough to do that... But I know munki has gurl.py which is a very nice python wrapper around it.

**Comment by sheagcraig** [comment]
@homebysix I removed the TODO since we have an issue for this.

I'm not feeling like making this change is super critical, unless someone feels really strongly about changing it.

**Comment by eahrold** [comment]
Yes, use gurl. My point was more to the effect that if we're using pyobjc for defaults there's no reason not to use other NS classes where we can.

**Comment by sheagcraig** [comment]
I mean-that would solve the SSL issues that are TODO'ed up in the code.
