### ISSUE TITLE
Respect SourceForge RSS feed rate limits

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#20]
SourceForge requires automated programs to limit themselves to one hit per 30 minutes per feed. In the scenario where somebody is repeatedly trying to create a SourceForge-based recipe, Recipe Robot could exceed this limit.

Potential options:

a. When the same RSS feed is tried a second time, issue an error and say "try again in X minutes."
b. Keep a local cache file of the RSS feed, and refer to that instead of the live version on subsequent runs.

Both rather complex.

**Comment by sheagcraig** [comment]
Geez. Yes. That seems excessively limited. One single request? Not one session/connection?

Alternate option: Just block SourceForge because of their recent sketchy behavior!

But seriously, I wouldn't want to cache the RSS; although I suppose it could get written as a cache file and used if both available AND the next request to SF fails.

Of course, that's not going to help you if you're done with one SF recipe and move on to the next one less than 30 minutes later.

Either way, I think it should be fairly easy to handle the response from SF and give a polite and descriptive error.

**Comment by homebysix** [comment]
I've packaged a few SourceForge based recipes recently, and haven't been rate limited. Let's revisit this if we ever see signs of limiting, but I think it should be pretty unlikely that people building SF based recipes will cause their servers undue stress.
