### ISSUE TITLE
How can we best validate the autopkg recipes we produce?

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#34]
Do we want to have Recipe Robot actually run the recipe and make sure the exitcode is zero? I'm leaning towards no, because of the risks of running newly-created .munki, .install, or .jss recipes on a production Mac.

**Comment by sheagcraig** [comment]
My argument is that in developing and testing RR on 1000's of products, you're slowly validating the output to a point where it's unlikely that some individual thing is going to deviate so horribly from the capabilities of RR to handle it that it's going to need validation.

I guess if you really wanted to, you could validate the package recipe and parent chain, since that has no side-effects on your system or management server. But, I think that's going to work, so there's no need.

Plus, it would slow things down A LOT.

**Comment by homebysix** [comment]
Agreed — it's been a few versions of RR ago since I saw it output a recipe that straight-up failed. More likely would be creation of a recipe that works but doesn't do what you intend (e.g. linking to a specific version's download URL). I think the readme will sufficiently cover the most common of those cases.
