### ISSUE TITLE
Design decision: Are we going to build on existing recipes?

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#37]
Recipe Robot was originally intended to utilize existing recipes as a foundation to build additional recipes. However, this seems like an incredibly complex thing to undertake:

- Many download recipes don't use code signature verification. Do other recipes we create need to start with code signature verification, or should that be the responsibility of the download recipe author?
- Some munki recipes were written before `ParentRecipe` existed, and therefore handle the entire download process too. Do we duplicate the download components into a new download recipe, then build pkg and other recipes on top of that?
- It wouldn't be sufficient to check whether the parent recipe has an Unarchiver processor, for example. We'd need to actually parse the destination path to figure out what the state of the cache directory will be when our recipes take over.

Given this, and given our initial time constraints, I'm starting to consider dropping this feature from the 1.0 release. Instead, Recipe Robot would only generate full recipe chains.

I still want to urge people not to build recipes that already exist and upload them to GitHub, in order to reduce confusion caused by recipe duplication in `autopkg search` results. Maybe this would mean that if any recipe exists, Recipe Robot will politely decline to build more (unless forced to build a full set).

**Comment by sheagcraig** [comment]
I vote for dropping it.

While I appreciate the reasoning behind it, I don't feel like Recipe Robot is intended to be an "easy button" to avoid having to use some common sense. As you point out, people are urged to not build recipes that already exist. Even someone who is relatively new to the scene, who is using Recipe Robot to generate recipes, is _probably_ going to have most of their needs already met by existing repos. For those new recipes they need to generate, we can give them warning messages about the situation.

_AND_ they're still going to need to know how to use git and GitHub to create their own repo, get their repo added to the AutoPkg org, and push everything up, before they're now in conflict with existing recipes. Hopefully at some point in the process of doing so they realize that their work is redundant. (And again-warning message).

Also, as you point out, some of the existing recipes are REALLY old and in need of being updated. I would love it if people were encouraged to put some pressure on the authors of those recipes to maintain their repos. Otherwise, I think they SHOULD be superseded by people crafting more up-to-date recipes who are going to maintain them. I don't think just because an early-adopter created a recipe for something that they get Conquistador rights for all time if they're not willing to govern their lands... Or some other metaphor.
