### ISSUE TITLE
Have RecipeIdentifierPrefix default to git user or mac user

### ISSUE THREAD

**Issue by jgstew** [homebysix/recipe-robot#63]
The function defined here is used to define the user identifier for the autopkg recipes: https://github.com/homebysix/recipe-robot/blob/master/scripts/recipe-robot#L372

It defaults to: **com.github.your_name_here**

It would be interesting if it could default to: **com.github.(configured git user)**

Typically this is contained in the file: `~/.gitconfig` or `~/.config/git/config` or `/etc/gitconfig`

The format is like an **INI** file, with sections, keys, values:

    [user]
        name = jgstew

Or else, it would default to: **com.github.( os.getusername() )**

**com.github.your_name_here** could be a fall back value.

--

### References: 
- http://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python
- https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
- http://stackoverflow.com/questions/8884188/how-to-read-and-write-ini-file-with-python
- https://bigfix.me/relevance/details/3003662
- https://bigfix.me/relevance/details/3003664

**Comment by jgstew** [comment]
On a side note, I created this:
http://orteil.dashnet.org/experiments/randomgen/?gen=https://gist.githubusercontent.com/jgstew/2edcb5b79c9d435d3c91/raw/bf6920f992c3914cfe0ebb44d49fa5ae87830036/random_robot.txt

The repo is here: https://gist.github.com/jgstew/2edcb5b79c9d435d3c91

Based upon: http://pastebin.com/raw.php?i=nqQSHHbj

**Comment by homebysix** [comment]
@jgstew I think the problem is that the `name` in the gitconfig file is arbitrary. Yours may match your GitHub username, but mine is `Elliot Jordan`.

In fact, I can't find any instance of my GitHub username in a predictable preference or config file on my Mac. I suspect GitHub uses the email address to refer to me, and GitHub's website/app does the translation from email to username.

I agree that using your local Mac shortname is better than `your_name_here` (a string that was chosen specifically because it didn't match any existing GitHub user, but who knows how long that will remain true).

**Comment by jgstew** [comment]
GitHub does not allow hyphens in the username, so `your_name_here` is an invalid option, which is probably a good thing in this case.
